export { Owner } from './owner.entity';
export { User } from './user.entity';
export { OTP } from './otp.entity';
export { Shop } from './shop.entity';
export { Device } from './device.entity';
export { Room } from './room.entity';
export { Reservation } from './reservation.entity';
export { ReservationSlot } from './reservation-slot.entity';
export { TimeSlotRate } from './time-slot-rate.entity'; 